server:
  port: 8083

  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices2
    username: root
    password: Vedaannoji@07
#    driver-class-name: com.mysql.cj.jdbc.Driver
    
  application:
        name: User Service 
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/connected-cars
       
        
